
const SUPABASE_URL = 'https://oewmbwqvcksflfkdgtvs.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ld21id3F2Y2tzZmxma2RndHZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ5MDIzMzIsImV4cCI6MjA4MDQ3ODMzMn0.ROC5YKffzQ4qQx1yQm4zi9aqI8wwChuvvP1ZFXNODRQ';

// Initialize Client
const _supabase = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);

const SupabaseService = {
    client: _supabase,

    // --- FETCH ALL DATA ---
    fetchAllValues: async () => {
        const [vendors, menu, orders, schedules, users, config] = await Promise.all([
            _supabase.from('vendors').select('*'),
            _supabase.from('menu_items').select('*'),
            _supabase.from('orders').select('*'),
            _supabase.from('daily_schedules').select('*'),
            _supabase.from('app_users').select('*'),
            _supabase.from('global_config').select('*').eq('key', 'main_config').single()
        ]);

        if (vendors.error) console.error("Error vendors", vendors.error);

        // Transform Vendors (sub_vendors -> subVendors)
        const formattedVendors = (vendors.data || []).map(v => ({
            ...v,
            subVendors: v.sub_vendors || [],
            banners: v.banners || [] // Ensure array
        }));

        // Transform Menu Items (addons jsonb -> array)
        const formattedMenu = (menu.data || []).map(m => ({
            ...m,
            vendorId: m.vendor_id,
            subVendor: m.sub_vendor,
            addons: m.addons || [],
            variants: m.variants || []
        }));

        // Transform Orders
        const formattedOrders = (orders.data || []).map(o => ({
            ...o,
            user: o.user_name,
            payer: o.payer_name,
            createdBy: o.created_by,
            vendor: o.vendor_name,
            subVendor: o.sub_vendor,
            item: o.item_name,
            paidAt: o.paid_at
        }));

        // Transform Schedules
        const formattedSchedules = (schedules.data || []).map(s => ({
            ...s,
            vendorId: s.vendor_id
        }));

        const globalConfig = config.data ? config.data.value : {};

        return {
            vendors: formattedVendors,
            menu: formattedMenu,
            orders: formattedOrders,
            dailyConfig: formattedSchedules,
            users: users.data || [],
            config: globalConfig
        };
    },

    // --- ORDERS ---
    addOrder: async (order) => {
        // Map frontend object to DB columns
        const payload = {
            id: order.id, // Using timestamp ID from frontend or let DB handle it? DB identity handles it usually, but frontend uses ID. Let's keep ID if provided, but identity is safer. 
            // Actually, keeping ID sync is tricky. Let's use the ID generated by frontend for now if BigInt allows, else we drop it and let DB gen.
            // Frontend uses Date.now() which is fine for BigInt.
            user_name: order.user,
            payer_name: order.payer,
            created_by: order.createdBy,
            vendor_name: order.vendor,
            sub_vendor: order.subVendor,
            item_name: order.item,
            addons: order.addons,
            remarks: order.remarks,
            price: order.price,
            status: order.status,
            date: order.date
        };
        const { data, error } = await _supabase.from('orders').insert([payload]).select();
        if (error) console.error("Error adding order", error);
        return data;
    },

    updateOrder: async (order) => {
        const payload = {
            user_name: order.user,
            payer_name: order.payer,
            created_by: order.createdBy,
            // vendor/item usually don't change in edit unless we re-select, but let's update all
            sub_vendor: order.subVendor, // might change
            addons: order.addons,
            remarks: order.remarks,
            price: order.price,
            status: order.status,
            payment_ref: order.paymentRef, // Add payment ref for history updates
            paid_at: order.paidAt // Add timestamp when paid
        };
        const { error } = await _supabase.from('orders').update(payload).eq('id', order.id);
        if (error) console.error("Error updating order", error);
    },

    deleteOrder: async (id) => {
        const { error } = await _supabase.from('orders').delete().eq('id', id);
        if (error) console.error("Error deleting order", error);
    },

    // --- SETTINGS (VENDORS) ---
    saveVendor: async (vendor) => {
        const payload = {
            name: vendor.name,
            description: vendor.description || '',

            banners: vendor.banners,
            sub_vendors: vendor.subVendors
        };

        // Check if exists (by ID) - Frontend IDs are timestamps or ints.
        // If it's a new vendor from frontend (Date.now()), we insert using that ID or let DB gen.
        // Let's rely on upsert.
        const { data, error } = await _supabase.from('vendors').upsert({ ...payload, id: vendor.id }).select();
        return { data, error };
    },

    deleteVendor: async (id) => {
        await _supabase.from('vendors').delete().eq('id', id);
    },

    // --- MENU ---
    saveMenuItem: async (item) => {
        const payload = {
            id: item.id,
            vendor_id: item.vendorId,
            name: item.name,
            description: item.description || '',
            price: item.price,
            sub_vendor: item.subVendor,
            addons: item.addons,
            variants: item.variants,
            is_active: item.isActive
        };
        const { error } = await _supabase.from('menu_items').upsert(payload);
        if (error) console.error(error);
    },

    deleteMenuItem: async (id) => {
        await _supabase.from('menu_items').delete().eq('id', id);
    },

    // --- USERS ---
    saveUser: async (user) => {
        const { error } = await _supabase.from('app_users').upsert(user);
        if (error) console.error(error);
    },

    deleteUser: async (id) => {
        await _supabase.from('app_users').delete().eq('id', id);
    },

    // --- SCHEDULE ---
    saveSchedule: async (config) => {
        const payload = {
            date: config.date,
            vendor_id: config.vendorId,
            cutoff: config.cutoff,
            status: config.status
        };
        const { error } = await _supabase.from('daily_schedules').upsert(payload);
        if (error) console.error(error);
    },

    deleteSchedule: async (date) => {
        await _supabase.from('daily_schedules').delete().eq('date', date);
    },

    // --- GLOBAL CONFIG ---
    saveGlobalConfig: async (cfg) => {
        const { error } = await _supabase.from('global_config').upsert({ key: 'main_config', value: cfg });
        if (error) console.error("Config save error", error);
    }
};
